baseURL = "https://www.darkheresy.co/"
title = "Dark Heresy"
author = "Matt Keathley"
copyright = "© 09-22 [Matt Keathley](https://www.keathley.co)"
languageCode = "en"
enableInlineShortcodes = true

theme = "risotto"

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params.theme]
palette = "base16-dark"

[params.about]
title = "dh2"
description = "A [Dark Heresy 2nd Edition](https://www.drivethrurpg.com/browse/pub/6/Fantasy-Flight-Games/subcategory/36_5218/Dark-Heresy) Group"
logo = "images/logo.svg"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
